language: java

before_install:
 - chmod +x gradlew

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

addons:
    srcclr:
        debug: true
